spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nerdsoncall_db
    username: postgres
    password: Jidnyesh@1210
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      maximum-pool-size: 5
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop # Creates tables automatically
    show-sql: true
    database: postgresql

server:
  port: 8080

logging:
  level:
    com.nerdsoncall: DEBUG
    org.springframework.security: DEBUG

razorpay:
  key-id: ${RAZORPAY_KEY_ID:zp_test_oaCoVv0RNgL6rf}
  key-secret: ${RAZORPAY_KEY_SECRET:u3MCboeH8t477SIkflHtQLyS}
